/** Rewrites example.expected.json from whatever the engine does right now.
 *
 *     npx tsx tests/fixtures/regenerate.ts
 *
 * Only run this when a change is *meant* to move the numbers, and read the
 * diff before you commit it -- the whole value of the snapshot is that
 * somebody looked.
 */

import { writeFileSync, readFileSync } from "node:fs";
import { simulate } from "../../src/lib";

const START = "2026-08-12";
const YEARS = 41;

const yamlText = readFileSync(new URL("../../src/example.yaml", import.meta.url), "utf-8");
const { completed, balances } = simulate(yamlText, { start: START, years: YEARS });

const snapshot = {
  note: "Generated by tests/fixtures/regenerate.ts -- see tests/regression.test.ts",
  start: START,
  years: YEARS,
  completed,
  balances,
};

const path = new URL("./example.expected.json", import.meta.url);
writeFileSync(path, `${JSON.stringify(snapshot, null, 2)}\n`);
console.log(`wrote ${path.pathname}`);
console.log(`  ${completed.length} milestones, ${Object.keys(balances).length} accounts`);
