name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths: ["infra/pulumi/**"]
  pull_request:
    paths: ["infra/pulumi/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Infra ${{ github.event_name == 'pull_request' && 'Preview' || 'Up' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/setup-pulumi@v2

      - name: Get infra role
        id: roles
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login
          echo "INFRA_ROLE_ARN=$(pulumi stack output infra_role_arn -s lukerohde/lukerohde-ingress/prod)" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$(pulumi stack output aws_region -s lukerohde/lukerohde-ingress/prod)" >> $GITHUB_OUTPUT

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.roles.outputs.INFRA_ROLE_ARN }}
          aws-region: ${{ steps.roles.outputs.AWS_REGION }}

      - name: Preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: make infra-preview

      - name: Apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: make infra-up
